version: '3'
services:
  router:
    build: ./router
    environment:
      - NODE_ENV=docker
    volumes:
      - ./db:/app/db
    networks:
      - mynetwork

  isp:
    build: ./isp
    environment:
      - NODE_ENV=docker
    volumes:
      - ./db:/app/db
    networks:
      - mynetwork

  rest-api:
    build: ./rest-api
    environment:
      - NODE_ENV=docker
    volumes:
      - ./db:/app/db
    networks:
      - mynetwork

  client:
    build: ./client
    environment:
      - NODE_ENV=docker
    volumes:
      - ./db:/app/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
