# Use Node.js image
FROM node:14

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY ./src ./src

# Copy SQLite database
COPY ../db ./db

# Expose port (if needed)
EXPOSE 3003

# Start the client app (adjust command as needed)
CMD ["node", "src/client.js"]
