# Start with a base Python image
FROM python:3.9-slim

# Set a working directory
WORKDIR /app

# Copy requirements.txt to the container
COPY requirements.txt .

# Install dependencies with CPU-only torch, without caching
RUN pip install --no-cache-dir fastapi uvicorn pydantic pandas numpy==1.26.4 gym shimmy gymnasium
RUN pip install --no-cache-dir torch==2.0.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install --no-cache-dir stable-baselines3
    
# Copy the rest of the application code
COPY src ./src

# Expose the FastAPI port
EXPOSE 8010

# Command to run FastAPI application with uvicorn
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8010"]
